### ISSUE TITLE
Can not run locally

### ISSUE THREAD

**Issue by edouin** [Domenicobrz/Lumen-2D#2]
Can not run by opening index.html. Only works with Node.js http-server.

index.html:1 Access to script at 'file:///C:/Lumen-2D-master/Lumen-2D-master/libs/main.js' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.

libs/main.js:1 Failed to load resource: net::ERR_FAILED

**Comment by Domenicobrz** [comment]
The project needs to be served from a local server to avoid CORS errors, as specified in the homepage :)

**Comment by Henelik** [comment]
@Domenicobrz What method did you use to run this locally?  I tried using a simple Python server, but keep getting a MIME type checking error.

**Comment by Domenicobrz** [comment]
@Henelik on VSCode I'm using an extension called "PHP Server (from brapifra)" which allows me to just right click on index.html and select: "PHP Server: Serve Project" to run the project locally at http://localhost:8080/index.html

Can I see the error you're getting?

**Comment by Henelik** [comment]
@Domenicobrz Sure.  Running with Python 3.7:

`python -m http.server`

and going to http://localhost:8080/index.html in Chrome, I get the following error in the Chrome console:

`:8000/libs/main.js:1 Failed to load module script: The server responded with a non-JavaScript MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.`

**Comment by Domenicobrz** [comment]
@Henelik Did you enable the chrome flag:
--enable-experimental-web-platform-features
?

**Comment by Henelik** [comment]
@Domenicobrz Yes, I did

**Comment by Henelik** [comment]
I got Lumen-2D running with a simple PHP server.  It's odd that Python didn't work correctly; it's supposed to have full ES6 support including module support, as far as I know.

**Comment by Domenicobrz** [comment]
@Henelik Yep for some reason it seems the python server is setting the MIME type of modules to text/plain and this isn't allowed hence the error you see..
Anyway I'm glad you got it running! have fun and if you can make something cool out of this library don't forget to share it! 😄
